### ISSUE TITLE
Can i add ChampData multiple parameter?

### ISSUE THREAD

**Issue by harpy2** [rithms/riot-api-java#17]
I love this project!

When i request "getDataChampion" , i dont know how to add multiple parameter
ChampData.ALL is so large size.

Riot api allow multiple parameter ChampData. ex) ChampData.Spell, ChampData.Passive

Can i?

**Comment by laazer** [comment]
Unfortunately this tool only has the one method for retrieving champion data. I agree with you that this can take up extra memory but it's also a solution that works in most scenarios. I personally am working on a modified version of the tool that can pull champion data with individual stats and I will share it once I have completed it.

**Comment by rithms** [comment]
This project allows for other ChampData parameter other than ChampData.ALL, just as the official API does.

You can read the ChampData constant source code here: https://github.com/rithms/riot-api-java/blob/master/src/constant/staticdata/ChampData.java

---------------------------------------------------------

I will push an update allowing multiple ChampData parameters to be used in the getDataChampion methods. I did not realize the official API did this.

**Comment by rithms** [comment]
An update for this issue has been released. All static data methods now support multiple data constant parameters.

## (Version 3.5.2)
### The following methods have been affected:

 **getDataChampion** methods can now take multiple ChampData constant
parameters.

 **getDataChampionList** methods can now take multiple ChampData constant
parameters.

 **getDataItem** methods can now take multiple ItemData constant parameters.

 **getDataItemList** methods can now take multiple ItemListData constant
parameters.

 **getDataMastery** methods can now take multiple MasteryData constant
parameters.

 **getDataMasteryList** methods can now take multiple MasteryListData
constant parameters.

 **getDataRune** methods can now take multiple RuneData constant parameters.

 **getDataRuneList** methods can now take multiple RuneDataList constant
parameters.

 **getDataSummonerSpell** methods can now take multiple SpellData constant
parameters.

 **getDataSummonerSpellList** methods can now take multiple SpellData
constant parameters.


You can view this release here: [(Version 3.5.2)](https://github.com/rithms/riot-api-java/releases/tag/v3.5.2)

**Comment by harpy2** [comment]
Perfect!

Thank you!
