### ISSUE TITLE
RiotApi class methods should be static

### ISSUE THREAD

**Issue by rithms** [rithms/riot-api-java#18]
I'm thinking of making the RiotApi class methods static. That way you don't need to instantiate an object such as:

**RiotApi api = new RiotApi("API-KEY");**
**Champion champ = getChampionById(1);**

instead you can just do:
**RiotApi.setKey("API-KEY");**
**Champion champ = RiotApi.getChampionById(1);**

Let me know if this kind of change is something you would like to see, or if you would have a problem with it, and why. 

I want to ask for feedback before making changes like this. I know some of you would have to refactor your existing code, but I think it would be for the better.

Let me know!

Rithms

**Comment by sergeknystautas** [comment]
I was going to submit a pull request to do the opposite... remove all static cases.  It's not very manageable to me if I can't instantiate an application cleanly and need to hack a static field at the right sequence.

**Comment by rithms** [comment]
Can you give an example of what you mean?

**Comment by fKunstner** [comment]
I would also advise against having more static methods.

The RiotApi is not completely stateless as it relies on (Key, Region, Season) to shorten queries.

For some programs querying multiple regions, having those properties static would need we either have to
- Set them before each call
- Use the long version of the queries with the region as parameter

wich is more overhead than creating an object with the key as parameter.

Furthermore, this would make multi-threaded use of the library more difficult as you can not rely on 
RiotApi.setRegion(EU)
RiotApi.getFoo()

to return values from EU, has it might have been changed in another thread in between.

An object with state and static methods is more or less a Singleton, and I don't think the current design is well suited for this.

A way I could see this work is if you'd remove all state with chained methods, holding only the Key as a state (wich could also be problematic if you want to use 2 test keys if your application is not validated yet), and chain calls like
RiotApi.getRegion("EU").getChampions(foo...)

If the problem you want to eliminate is the constant use of the key, you could create a getApi() factory method that would create the RiotApi object based on a java .properties file holding the key.

**Comment by laazer** [comment]
I agree with fKunstner on this, but for the sake of discussion what do you think one would gain from making those methods static?

**Comment by rithms** [comment]
I see what you mean fKunstner, I didn't take those things into consideration.

**Comment by sergeknystautas** [comment]
initialize a servlet, it needs a database connection, whatever else, it needs to load some static data.  How do I know it's ready to get the static data because the API is set?

That's just a trivial example.  Any app with more than a few dependencies becomes unmanageable to control the dependencies when code uses static.  You just end up having to create your own non-static objects that call the static behind the scenes.

**Comment by rithms** [comment]
Okay, thanks for the feedback guys. :)
