### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rithms** [rithms/riot-api-java#21]
Change getSummonerByName() and getSummonerById() methods to return single Summoner object instead of a Map with one entry.

Update the keys of Map<String, Summoner> returned by getSummonersByName() methods to be case-insensitive.

Still adding onto the list, feel free to make suggestions.

**Comment by jluzonpr** [comment]
Woooow, I've been meaning to make this change and make a PR since December
and never got around to it. Awesome.

**Comment by rithms** [comment]
getSummonerByName, getSummonerById(), and getSummonerName() methods have been updated to meet these changes. (v3.5.6)

I've changed my mind regarding the need for case-insensitive keyed Maps.
Might come back to it later.

Since there are no further suggestions, I will close this issue for now.

Thanks!
