### ISSUE TITLE
Advice on Hiding API key

### ISSUE THREAD

**Issue by jaimehrubiks** [rithms/riot-api-java#25]
Hello, I've created my first application and I am planning on asking for my production APi key. I wonder if you could tell me some advice on hiding it. I mean, I don't want to invest too much effort in this, but at least some basic protection would be great.
Thanks.

**Comment by jluzonpr** [comment]
Hey Jaime,

You should hide it by putting it in a backend server which your client
communicatesnto, and not have your client communicate directly with the
Riot API.

**Comment by laazer** [comment]
No matter what you do, just remember to add whatever file is holding your key to your gitignore file

**Comment by jaimehrubiks** [comment]
This is a desktop app, it won't go on git at the moment at least. The backend server idea sounds good, but because of the low scale of this  new app it is not worth the effort.

**Comment by jluzonpr** [comment]
Right now it is the only correct way to do it. Even if you compile your API
key in, and don't release it in the source code, someone can decompile it
and get it.

**Comment by rithms** [comment]
Unfortunately the responses hear are correct. You will need to create a proxy server to act as an intermediary.

**Comment by jaimehrubiks** [comment]
I understand what is said here, either decompiling the app or even ssl-mitm-ing would reveal the key for sure. However it is a shame having to maintain a server for a small app that you don't even know if it would have some users or not yet. 
On the other hand, having a proxy server will bring more troubles, like you'd need to authenticate somehow the client  with it so that no one can use that server apart from your app, not doing so would be the same situation as giving your rior api key away.

Thanks for your answers.

**Comment by sergeknystautas** [comment]
Moreover you don't want to bundle your API key into the desktop app since they you could not update it without forcing your users to download a new version of your software (or at least a configuration file, which would be even easier to pick up).

**Comment by jaimehrubiks** [comment]
I ended up setting a server up and exchanging info using sockets and serialized data, then the server only implements this riot-api-java. The result is here
http://eldoctordeldesierto.com/leagueinfo/
if anyone needs help on this I answer questions.
