### ISSUE TITLE
Add support for Tournament API when available.

### ISSUE THREAD

**Issue by rithms** [rithms/riot-api-java#36]
Riot [announced](https://developer.riotgames.com/discussion/announcements/show/1ELjVyln) a new Tournament API. [Documentation here](https://developer.riotgames.com/docs/tournaments-api).

Reminder to self - Add support for the endpoints when the API is available.

**Comment by rithms** [comment]
Have most of the code written already. Waiting for approval for demo Tournament API key to test everything and make sure it works properly.

Will push tomorrow.

**Comment by Linnun** [comment]
Thanks for the heads-up. Please let me know when you push by adding another comment here.

**Comment by rithms** [comment]
I have made the push.
https://github.com/rithms/riot-api-java/releases/tag/v3.8.0
