### ISSUE TITLE
getMatchList with fewer paramaters

### ISSUE THREAD

**Issue by evanhk** [rithms/riot-api-java#42]
Hi,

Looking at the Riot API Reference I should be able to get a MatchList using {Region,Summoner ID, RankedQueues} or {Region,Summoner ID, RankedQueues, Season} (along with a few other combinations) but you only have it implemented for the following parameter combinations:

(Region ,summonerId, championIds, rankedQueues, seasons, beginTime, endTime,	beginIndex, endIndex)                                                                                                                   
(Region , summonerId)
(summonerId, championIds, rankedQueues, seasons, beginTime, endTime, beginIndex, endIndex)
(summonerId)

Is it the implementation or my lack of knowledge that's hindering me here?

THANKS FOR THE (otherwise) AWESOME LIBRARY

Cheers

**Comment by evanhk** [comment]
After looking into it a little more I can put pretty much MAX_INT as end Index and 0 as start Index, and 0, current time for the time parameters. As long as I specify the season/queue It will return what I want.

Thought I'd leave this here in case it helps anyone.

**Comment by rithms** [comment]
If you call getMatchList(Region region, long summonerId) it should give you a list of all your matchIds. No need to input the additional index parameters the way you described.
