### ISSUE TITLE
Process 'command 'C:\Program Files (x86)\Java\jdk1.8.0_65\bin\java.exe'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by rithms** [rithms/riot-api-java#43]
Got this email - 

> Hi man

> I am currently working with an older version of the library and it works perfectly, but the newer version released about 25 days ago and the current one prevents me from launching any android project which has it as a dependency. I have recreated this scenario on five different systems and neither of them is able to launch.

> The error is as follows: 
```
Error:Execution failed for task ':app:preDexDebug'.
com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files (x86)\Java\jdk1.8.0_65\bin\java.exe'' finished with non-zero exit value 1
```

> After researching the error, it appears there are multiple possible causes. I might’ve been on the wrong track with the aforementioned ‘unused icons’ but I just wanted to inform you of this issue.

> Hope it helps and keep up the great work.

> Cheers

**Comment by rithms** [comment]
I told him we recently updated to Java 8 and added it as a dependency, but I'm not entirely sure that's the root of his issue. I asked him more questions and am going to keep looking into it.

**Comment by jluzonpr** [comment]
You wouldn't use the Java JDK on Android so there might be a hardcoded
dependency somewhere.

**Comment by rithms** [comment]
I have released a new Android version for 3.8.2. In this version I reverted all Java 8 code to Java 7, fixing the issues Android developers are having with using the library in Android Studio.

I believe this issue to be caused by the support/requirements of Android Studio, and the difference of bytecode generated between Java 7 and Java 8.

The release can be found [here](https://github.com/rithms/riot-api-java/releases/tag/v3.8.2-android).

**Comment by Linnun** [comment]
Should we generally make this api work in Java 7 then?

**Comment by rithms** [comment]
Maybe. It's only 2 utility methods that use Java 8 features.
Otherwise we can just release two separate versions.

**Comment by Linnun** [comment]
We use String.join() at least 10 times. That's a JDK 1.8 method.

**Comment by rithms** [comment]
Oh yeah, you're right.

**Comment by rithms** [comment]
This issue has been fixed. Further discussion about Java version will be made in issue #46
