### ISSUE TITLE
Java 7 support?

### ISSUE THREAD

**Issue by sergeknystautas** [rithms/riot-api-java#46]
I started using this library a while ago when Java 7 was still supported and I can't readily move to Java 8.  I can't find a discussion of why Java 7 support was dropped and so was wondering if there's interest in me removing the Java 8 requirement?  I can make the changes and create a pull request if so.

**Comment by rithms** [comment]
Was just discussing this in this issue: https://github.com/rithms/riot-api-java/issues/43

**Comment by sergeknystautas** [comment]
I use this library in a app that runs on Google App Engine, which currently only supports Java 7.

**Comment by rithms** [comment]
I'll work on the rewriting the library to remove the Java 8 requirement over the weekend then.

**Comment by Linnun** [comment]
we should be compatible with Java 7 now: https://github.com/rithms/riot-api-java/commit/678c2af2ea016668de784fa66056c270445d52d7

So far it seems to work for me, might need further testing though.

**Comment by Linnun** [comment]
I did some further testing, and this seems to work flawlessly so far, even on Java 6 and Java 5. Java 4 and older does not work though.

**Comment by sergeknystautas** [comment]
I think the maven pom is still specifying 1.8 for the compiler, but in eclipse everything compatible with Java 1.7 for me.  Thanks for the quick turnaround!

**Comment by Linnun** [comment]
Whoops. I got nothing to do with Maven, so I forgot about that.

Should be done now :)

**Comment by sergeknystautas** [comment]
Yeah, I actually use eclipse and ant but just noticed that as I was merging my fork.  Thanks again for the quick updates!

**Comment by Linnun** [comment]
With this being done, I don't think we still need the android branch.

(On a side note, I generally consider the download link in the readme obsolete, since it's hosted on Github now, and we also provide releases here)

**Comment by rithms** [comment]
Agreed. I have removed the android branch.
The download link in the README directs to the releases page. Should we remove it from the README? I feel like people unfamiliar with GitHub might find it useful.

**Comment by Linnun** [comment]
Seems like an unnecessary release step to me - but keep it in, if you're fine with having that in your release process.
I think we're done here.
