### ISSUE TITLE
The import net cannot be resolved 

### ISSUE THREAD

**Issue by ChrisYG** [rithms/riot-api-java#47]
Hi,

I'm not an expert at Java, but I found this problem when using the code:
I set up the jar file as suggested in the readme and used the example code, but an error "The import net cannot be resolved" occurred. 

I guess this is probably because there's no "net" folder within the jar file, but only "constant", "dto.xxx", "main.java.riotapi", etc. 

I'm not sure if this is my own fault, or if the example usage should be updated. Any suggestion appreciated!

**Comment by rithms** [comment]
The download link in the README was not updated properly and directed to an old version of the JAR, before package names were updated. The README has now been updated.

For future reference, the latest JAR can always be found on the [releases page][https://github.com/rithms/riot-api-java/releases].

Thank you for bringing this to our attention. :+1:
