### ISSUE TITLE
Empty jar after change structure 24.12

### ISSUE THREAD

**Issue by Murik** [rithms/riot-api-java#48]
by maven convension u need to have structure like
src/main/java	 -> Application/Library sources

https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

after move all classes one level up u need to specify source folder in pom
    <sourceDirectory>src</sourceDirectory>

or  just revert commit "a79be2b Linnun on 24.12.15 at 0:02
Fixed paths for the new packages" :)

**Comment by Linnun** [comment]
I don't use maven and don't plan to - but does this fix the issue?

https://github.com/rithms/riot-api-java/commit/e5535e044cb7fdea0ef5e67a24036778c8cf8d6a

No idea why this was commented out.

**Comment by Murik** [comment]
I commented out this line when committed correct maven structure  (see ad944d3c302014e45ac224184528508cc0efc12e )

next problem after specify source folder - it is tests.
junit has a scope  test  in pom.xml
it mean - lib injects only to the folder  src/test/java.

quick fix - comment out the line `<scope> test </ scope>` too.
But I would still recommend to go back in the correct structure.
Thx

**Comment by rithms** [comment]
I went ahead and commented out the scope for now. https://github.com/rithms/riot-api-java/commit/d79a4a02b8cab975fb3ca584642f2200b95cdb7d

**Comment by Linnun** [comment]
https://github.com/rithms/riot-api-java/commit/57328bb800f67387ba5c186b37ea366136a9be97

Can someone tell/test, if this fixes the issues with maven you experienced?

**Comment by Murik** [comment]
seems all fine!
tag <sourceDirectory>src/main/java</sourceDirectory> yet not nessesary. is it the same by default.

tips: to properly work in IDEA just need to reimport maven project in panel.

& now can't recompile with demo key^ because of RateLimitException in test) but it now nessesary
