### ISSUE TITLE
How to get Player icon

### ISSUE THREAD

**Issue by JonZarate** [rithms/riot-api-java#51]
I can get the ID of the icon but not the icon itself. 

How should I do it ?
Thanks.

**Comment by rithms** [comment]
You need to download the tar ball file off of ddragon and host the files on your server:
http://ddragon.leagueoflegends.com/tool/

The image files are named after the corresponding ID.

or use the ddragon CDN to serve the files.

**Comment by JonZarate** [comment]
I found this format:
http://ddragon.leagueoflegends.com/cdn/{version}/img/profileicon/{profileiconid}.png

What works great when I try my icon:
http://ddragon.leagueoflegends.com/cdn/6.3.1/img/profileicon/27.png

Isn't there a function in the API than returns an ImageIcon or something ? Are you planning to add it ? If I add it, would you include it in the code ? 

Thanks.

**Comment by rithms** [comment]
We never planned to have the library serve the actual image files, just serve IDs which are kept updated via Riot's API. It is expected that developers handle and update their own assets (whether they are using ddragon or hosting the files themselves).

**Comment by JonZarate** [comment]
I guess it's the same with champ icons ?

**Comment by Linnun** [comment]
Yes, it's the same for all assets.

**Comment by JonZarate** [comment]
@Linnun Then, why does a getImage() function exist in champion class ?

**Comment by rithms** [comment]
getImage() returns an Image object with data about the champions's image.

For example, the name of the image file found on ddragon, and the dimensions of the image.

**Comment by JonZarate** [comment]
@rithms That is nice, however, I am getting a null object from that function. Is that intended ?

**Comment by rithms** [comment]
By default the static data champion API only returns information like champion ID, name, and key. 
Which is pretty smart on Riot's part. Why give you data you don't want? It's a waste.
To get more data, you must specifically request it using the available query parameters.

You are probably using the method that specifies no query parameters:
**getDataChampionList(Region region)**
So you are only getting back a Champion object with an ID, name, and key. Everything else you didn't specify is null.

You can use the overloaded method:
**api.getDataChampionList(Region region, String locale, String version, boolean dataById, ChampData... champData)**

to ask for more information:

For example, to get champion image data:
```
ChampionList championList = api.getDataChampionList(Region.NA, null, null, false, ChampData.IMAGE);
```

or, to get champion image data, and information about champion skins:
```
ChampionList championList = api.getDataChampionList(Region.NA, null, null, false, ChampData.IMAGE, ChampData.SKINS);
```

or to get ALL champion data, without having to specify each individual parameter:
```
ChampionList championList = api.getDataChampionList(Region.NA, null, null, false, ChampData.ALL);
```

**Comment by JonZarate** [comment]
Oh great ! I though it was not intended but it definitely makes sense. 

In order to avoid this kind of "code info" issues, is there any documentation of the code ?

Thank you.

**Comment by rithms** [comment]
The javadocs can be found [here](http://rithms.net/riot-api-java/doc/).
