### ISSUE TITLE
Games ordered by time

### ISSUE THREAD

**Issue by JonZarate** [rithms/riot-api-java#52]
I realised the games are returnes in a Set, not a List. Thus, they are not ordered.

Is there a way to get them ordered or do we have do it ourselfs ?

Thank you.

**Comment by rithms** [comment]
You would have to do it yourself.

You're talking about the getRecentGames() method.
This method uses the game-v1.3 endpoint of the Riot Games API.
The documentation for the endpoint specifies that the data type used for the games is a Set<Game>.
When I first created the library I stuck strictly to this documentation to make it as consistent as possible.

As time went on, we have improved the library and deviated from the documentation if it makes more sense and provides convenience for developers.

Regardless of the documentation, the endpoint returns the games in a JSON array, and it looks like it is ordered, I see no reason why we cannot update the library to return a List instead. With that said, we are currently working on version 4 of the library which includes some pretty major changes.
So you won't see any updates like this till version 4 is released.

**Comment by JonZarate** [comment]
@rithms Is there a set date for the version 4 release ? I mean, I just have to sort by "CreateDate" but I am curious about some other features.

I guess this should work:
`	public static ArrayList<Game> orderGamesByTime(Set<Game> games){
		Game list[] = new Game[games.size()];
		ArrayList<Game> orderedList = new ArrayList<Game>();
		
		Iterator<Game> iterator = games.iterator();
		for ( int i = 0; iterator.hasNext(); i++){
			list[i] = iterator.next();			
		}
		
		for ( int i = 0; i < list.length; i++){
			
			int lowestDate = 0;
			for (int a = i ; a < list.length; a++){
			
				if ( list[a].getCreateDate() > list[lowestDate].getCreateDate() ){
					lowestDate = a;
				}
				
			}	
			
			orderedList.add(list[lowestDate]);
			list[lowestDate] = list[i];
		}
		
		return orderedList;
	}`

**Comment by rithms** [comment]
There's no specific date set.

I answered your question about the Champion static data API in the other issue you asked - https://github.com/rithms/riot-api-java/issues/51#issuecomment-186590937

**Comment by JonZarate** [comment]
Yep, just read it. Thanks.
