### ISSUE TITLE
How can we get the placements stats ?

### ISSUE THREAD

**Issue by JonZarate** [rithms/riot-api-java#53]
If you try to get the rancked information of a unrancked summoner, even if he has played some placement games it returns nothing.

Is this possible?

Thanks.

**Comment by rithms** [comment]
Ranked Stats won't return anything until a summoner has finished their placements and is officially ranked in a league.

**Comment by rithms** [comment]
I take my previous response back.

getRankedStats should return information for a summoner in their placements.

Can you provide the code you are using?

**Comment by Linnun** [comment]
I'd like to add that specifically the leagues endpoint will always return an empty dataset until your are actually placed in a league (for obvious reasons).

rithms already provided a way to get ranked stats, which will also work if a summoner is still to be placed.

**Comment by JonZarate** [comment]
Yes, I was getting a null league entry, I will try the function rithms suggested. 
Thank you.

**Comment by JonZarate** [comment]
I just realised. I can't see how many W/L the summoner has in RankedStats. Is it supposed to be there ? I can't find it.

**Comment by Linnun** [comment]
I have added an example script that should achieve your desired data:

https://github.com/rithms/riot-api-java/blob/master/examples/RankedWinsAndLosses.java


Please just let me know, if you need help with anything else.

**Comment by rithms** [comment]
Wins and losses can be retreived from the totalSessionsWon and totalSessionsLost fields.

As you can see from my example above, RankedStats divides stats by champions. The 'id' field is the champion ID of the champion for those stats. A champion ID of 0 means overall stats.

**Comment by rithms** [comment]
That example might not work for him, as it is using version 4 features like the ApiConfig. I believe he's using the v3.9.0 jar form the releases page.

**Comment by Linnun** [comment]
It should work with 3.9.0, if you replace

```
		ApiConfig config = new ApiConfig().setKey("YOUR-API-KEY-HERE");
		RiotApi api = new RiotApi(config);
```

with

`		RiotApi api = new RiotApi("YOUR-API-KEY-HERE");`

**Comment by JonZarate** [comment]
Yes I am using the one from the release page but I had no problems to initialize the API. The code is working too, thank you. I didn't figure out the first  id was for overall data.
