### ISSUE TITLE
getRegionByName

### ISSUE THREAD

**Issue by JonZarate** [rithms/riot-api-java#54]
I don't have this function in my JAR, was it added in the 4.0 version ? As you said I have the 3.9 so I suspect that's the problem. In case it is, is there any link to download it ?

Thank you.

**Comment by Linnun** [comment]
Yes, that method is new in 4.0. Version 4.0 is currently an alpha version, meaning it's not recommended to use this in a productive environment. (Even though I do. Living on the edge, heh.)

For now, you can manually create a method like that:

```
	public static Region getRegionByName(String name) throws RiotStringNotFoundException {
		for (Region region : Region.values()) {
			if (region.getName().equals(name.toLowerCase())) {
				return region;
			}
		}
		return null;
	}
```

To use the latest version of the master branch, you can also fork/download this repository.

**Comment by JonZarate** [comment]
Sure, you forgot to erase the exception, but yes, I will just add the code and wait for the release.

What are you using the api for ?

**Comment by Linnun** [comment]
Whoops, removed the throws statement.

I'm the founder and CEO of LoLSkill.net - some of our backend applications run in Java and use this API wrapper.

**Comment by JonZarate** [comment]
Wow that's a good website. Are those adds enough to keep it up ? 

What kind of key do you have to execute such a big amount of "querys" ?

**Comment by Linnun** [comment]
Yep, the current page view numbers are high enough to monetize the project and earn a living with advertising. Infact, LoLSkill is my 'main' full-time job since more than a year now. (Besides that I'm translating Steam and games to German for Valve)

LoLSkill has an extended api key, not using the default limits.

**Comment by JonZarate** [comment]
That's amazing man, congrats on that. I am currently livin in Germany, no ida of German tho. 
How did you get to translate for Valve ? Do you have any "language license" or just a native speaker ? I would do it for Spanish too ! haha 
By the way, how did you get the extended api key ? And how many visitors do you have per month in the website ? How many are neccesary to earn (let's say) 2000 € (or $) ?

**Comment by Linnun** [comment]
I'm born and raised in Germany, so I'm a native speaker.

You can request an extended api key from Riot, if your api is regularly hitting the limits and you have a huge user base to serve.
The amount of page views needed to acquite a given goal depends on many factory. It's probably best to ask your advertising partner about the details.
