### ISSUE TITLE
Missing files in Jitpack Release v3.9.0

### ISSUE THREAD

**Issue by brunokenshin** [rithms/riot-api-java#58]
Hey,
Just for Knowledge, I had some problems when I tried to get the lib (release v3.9.0) by Jitpack. I looks like I'm getting only the Manifest and pom files. All the classes are missing.

I tested with the release v3.8.2 and works fine!

Nice Lib btw. Congratulations!

**Comment by Linnun** [comment]
This is a duplicate to https://github.com/rithms/riot-api-java/issues/48

This issue will be fixed with release of 4.0.
