### ISSUE TITLE
Service unavailable

### ISSUE THREAD

**Issue by hakangs** [rithms/riot-api-java#59]
I am trying to get a champion's static data with my development key:

```
ApiConfig ac = new ApiConfig();
ac.setKey("MY API KEY");
RiotApi api = new RiotApi(ac);
net.rithms.riot.api.endpoints.static_data.dto.Champion champData = api.getDataChampion(Region.TR, 98);
```

But I get the following error :

```
net.rithms.riot.api.RiotApiException: Service unavailable
	at net.rithms.riot.api.request.Request.execute(Request.java:155)
	at net.rithms.riot.api.request.Request.<init>(Request.java:88)
	at net.rithms.riot.api.EndpointManager.callMethodAndReturnDto(EndpointManager.java:57)
	at net.rithms.riot.api.RiotApi.getDataChampion(RiotApi.java:580)
	at net.rithms.riot.api.RiotApi.getDataChampion(RiotApi.java:599)
```

But when I use Postman, I can get the result and service is available.

What can be the problem ?

**Comment by rithms** [comment]
The problem is on Rito's side. Seems like they've been having a couple issues lately.

When I first tested it out I was receiving 503s.
Minutes later I am now receiving 200s.
Seems unstable.

(I tested it using the library, developer portal, and Postman. All shared the same behavior)

**Comment by hakangs** [comment]
Thank you, and sorry for opening an issue :(

**Comment by rithms** [comment]
No problem. It's good for us to check to make sure it's not a problem on our side.
