### ISSUE TITLE
Create the javadoc and show in gh-pages

### ISSUE THREAD

**Issue by willmenn** [rithms/riot-api-java#63]
Hi, 
It would be nice to create the **javadoc** and put into the branch **gh-pages**.
 if you put the **javadoc** into a branch called **gh-pages** the **github** will publish your static files for free.
A sample for the folders, you could delete all the classes in the gh-pages branch and add the javadoc into a folder called gh-pages in your master branch.
```
-gh-pages
-examples
-src
LICENSE.txt
README.md
pom.xml

**Comment by rithms** [comment]
The javadocs should already be available via the gh-pages branch. 

You can acces them through the following link: http://rithms.net/riot-api-java/doc/

If something is missing or you would like to see any changes, let us know.
