### ISSUE TITLE
RiotApiAsync object is missing

### ISSUE THREAD

**Issue by vBandiTv** [rithms/riot-api-java#65]
Hi rithms!

I was looking at you'r Async request example, and wanted to try it, the problem is that i dont have a `RiotApiAsync` object at - net.rithms.riot.api package.
I'v downloaded the latest jar file, and it missing there too.
Is it an object that should be in the jar? Or should I create it by my self?

One more question - I'v already made some project that is working fine, the problem is that i am getting a lot of "Rate limit exceeded" Exceptions. To avoid it I used the `Thread.sleep(xxxx)` method before every request to riot, is the Async way can help me to avoid the sleep method?

Thx in Advance!

**Comment by Linnun** [comment]
The latest jar download is the stable version 3.9.0.

The master branch is currently at version 4.0.0 alpha, and had some mayor changes in how it works. The examples of the master branch are for using the upcoming version 4.0.0 and don't work for version 3.9.0 or older.

**Comment by vBandiTv** [comment]
Thx for the answer!
