### ISSUE TITLE
Static Data

### ISSUE THREAD

**Issue by osimon8** [rithms/riot-api-java#67]
Attempting to use methods such as getSpells() or getTags() on (static data) Champion objects just returns null. However, some methods work, such as getName(). I'm not sure if this is an issue with this library, Riot's API, or myself, but it is preventing me from working on the project I am working on. Thanks!

**Comment by rithms** [comment]
A lot of the static data endpoints don't return all the data by default, so you will have to specifically request it using the ChampData/SpellData/ItemData parameter.

For example, the champion endpoint will only return basic information such as champion name, key, id and title.

When you use the overloaded method **getDataChampionList(Region)** without the ChampData parameter, you will just get this default information, and everything else will be 0-false-null.

If you want information like image, skin, or lore data, you will have to use **getDataChampionList(locale, version, dataById, champData)**, providing the kind of ChampData you want to the champData parameter.

Here is an example, printing out all the skin names of each champion:
```java
import net.rithms.riot.api.RiotApi;
import net.rithms.riot.api.RiotApiException;
import net.rithms.riot.constant.Region;
import net.rithms.riot.constant.staticdata.ChampData;
import net.rithms.riot.dto.Static.Champion;
import net.rithms.riot.dto.Static.ChampionList;
import net.rithms.riot.dto.Static.Skin;

public class Example {

	public static void main(String[] args) throws RiotApiException {
		// TODO Auto-generated method stub
		RiotApi api = new RiotApi("API-KEY", Region.NA);
		ChampionList championList = api.getDataChampionList(null, null, false, ChampData.SKINS);
		for(Champion champion : championList.getData().values()) {
			System.out.println(champion.getName());
			for(Skin skin : champion.getSkins()) {
				System.out.println(skin.getName());
			} System.out.println("======");
		} 
	}
}
```

Note you can provide multiple ChampData values, or can use **ChampData.ALL** if you want to receive all data.

Hope this helps.

**Comment by osimon8** [comment]
Thanks so much!
