### ISSUE TITLE
Problem with some field naming (inconsistency, missing setters)

### ISSUE THREAD

**Issue by briceambrosiak** [rithms/riot-api-java#72]
I was digging in the API, and doing some serialization of retrieved data (champion's data) to not always contact the API. But this process fails (in my case, using Jackson) because some fields have a different naming than their getters.

I've stumbled upon this in `net.rithms.riot.dto.Static.Stats` (from `net.rithms.riot.dto.Static.Champion`).
Fields are name like 'hpregenperlevel', 'movespeed', etc. when the getters are named `getHpRegenPerLevel()`, `getMoveSpeed()`, etc.

This breaks my serialization/deserialization process, but also lacks of consistency.
Also, why not putting some setters with same names than getters? There is no problem of putting setters in a DataObject like this (this could have saved me).

I don't know if other objects are like this.

Thanks,

**Comment by rithms** [comment]
There's an open issue about the setters - https://github.com/rithms/riot-api-java/issues/69

I will look into the naming convention inconsistency/issue.

**Comment by rithms** [comment]
I have removed all of the unconventional field names in DTOs brought on from the inconsistencies found across endpoints in the Riot Games API. GSON will now map certain field names returned from the API to member variable names that follow the Java convention.

This means you should no longer have any issues using libraries like Jackson which assume a specific POJO convention.

Let me know if you run into any more problems regarding this issue. Please verify that this issue has been solved, so this issue can be closed.

The commit for these changes can be found here: https://github.com/rithms/riot-api-java/commit/255e431867077d3a193e700f8a9cb99ecdf50d22
Thanks.

**Comment by rithms** [comment]
Serialization/Decentralization code snippet: 

```java
import net.rithms.riot.api.ApiConfig;
import net.rithms.riot.api.RiotApi;
import net.rithms.riot.api.RiotApiException;
import net.rithms.riot.api.endpoints.static_data.constant.ChampData;
import net.rithms.riot.api.endpoints.static_data.dto.Champion;
import net.rithms.riot.constant.Region;
import java.io.IOException;

import org.codehaus.jackson.JsonGenerationException;
import org.codehaus.jackson.map.JsonMappingException;
import org.codehaus.jackson.map.ObjectMapper;
import org.codehaus.jackson.map.SerializationConfig;

public class Example {

	public static void main(String[] args) throws RiotApiException {
		ApiConfig config = new ApiConfig().setKey("API-KEY-HERE");
		RiotApi api = new RiotApi(config);
		
		ObjectMapper mapper = new ObjectMapper();
		mapper.enable(SerializationConfig.Feature.INDENT_OUTPUT);
		
        String json;
        Champion champion;
		try {
			
			champion = api.getDataChampion(Region.NA, 104, null, null, ChampData.STATS);
			System.out.println(champion);
			
			json = mapper.writeValueAsString(champion);
			System.out.println(json);
			
			champion = mapper.readValue(json, Champion.class);
			System.out.println(champion);

		} catch (JsonGenerationException e) {
			e.printStackTrace();
		} catch (JsonMappingException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
		
	}
}
```

Output:
```
103: Ahri
{
  "allytips" : null,
  "blurb" : null,
  "enemytips" : null,
  "id" : 103,
  "image" : null,
  "info" : null,
  "key" : "Ahri",
  "lore" : null,
  "name" : "Ahri",
  "partype" : null,
  "passive" : null,
  "recommended" : null,
  "skins" : null,
  "spells" : null,
  "stats" : {
    "armor" : 20.88,
    "armorPerLevel" : 3.5,
    "attackDamage" : 53.04,
    "attackDamagePerLevel" : 3.0,
    "attackRange" : 550.0,
    "attackSpeedOffset" : 0.0,
    "attackSpeedPerLevel" : 2.0,
    "baseAttackSpeed" : 0.625,
    "crit" : 0.0,
    "critPerLevel" : 0.0,
    "hp" : 514.4,
    "hpPerLevel" : 80.0,
    "hpRegen" : 6.505,
    "hpRegenPerLevel" : 0.6,
    "moveSpeed" : 330.0,
    "mp" : 334.0,
    "mpPerLevel" : 50.0,
    "mpregen" : 6.0,
    "mpRegenPerLevel" : 0.8,
    "spellBlock" : 30.0,
    "spellBlockPerLevel" : 0.0
  },
  "tags" : null,
  "title" : "the Nine-Tailed Fox"
}
103: Ahri
```

**Comment by rithms** [comment]
Let us know if you run into any more issues regarding this.
