### ISSUE TITLE
[Enhancement] Replace 'String locale' with Locale locale or new internal RiotLocale object

### ISSUE THREAD

**Issue by briceambrosiak** [rithms/riot-api-java#73]
In methods such as `Champion getDataChampion(int id, String locale, String version, ChampData... champData)`, the `locale` value is a `String`. Using the library, you don't necessarily know what String to put : "fr", "FR", fr-FR", fr_FR", etc. ?

An improvement of this could be passing a `Locale` object, and then internally call the `toString()` conversion method to get 'fr_FR'. But this still leaves us with the problem of a user passing `Locale.FRENCH` instead of `Locale.FRANCE` : you'll end up with String 'fr' instead of 'fr_FR' required by the Riot API.

So I think the best alternative is to add your custom `RiotLocale` enum in your library, that would contains all the locales supported by the API, and change your methods signature to support this instead of String.

=> `Champion getDataChampion(int id, **RiotLocale locale**, String version, ChampData... champData)

What do you think of this?
Thanks.

**Comment by rithms** [comment]
For reference, the list of valid locale codes is available on the Riot Games API [Static Data Documentation](https://developer.riotgames.com/docs/static-data) page.

It wouldn't hurt to add an enum for the static data locale code parameter. We already do it for other parameters like champ/item/rune/mastery data.

**Comment by Linnun** [comment]
https://github.com/rithms/riot-api-java/commit/449fe02a24c4decbf907fada0fe9cbc3a66cf982
