### ISSUE TITLE
Readme incorrectly states to use an invalid constructor

### ISSUE THREAD

**Issue by jfisher446** [rithms/riot-api-java#82]
Readme states in several places to call:
`RiotApi api = new RiotApi("YOUR-API-KEY-HERE");`

However, there is no RiotAPI(String) constructor.

**Comment by rithms** [comment]
Which version of the library are you using?

**Comment by jfisher446** [comment]
I see that now. I wrote this based on the current code base, which seems significantly different. Disregard.

**Comment by rithms** [comment]
Yeah, we should really have a development branch. Sorry about that.
